// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./src/components/codemirror/CodeMirror.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    Preview: typeof import('./src/components/preview/preview.vue')['default']
  }
}

export { }
